version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./codeigniter_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localhostroot
      MYSQL_DATABASE: sampleDB
  ciapp:
    build: ./codeigniterapp
    volumes: 
      - ./codeigniterapp:/var/www/html/codeigniterapp
    depends_on:
       - db
    restart: always
    links:
      - db:mysql
    ports:
      - "8000:80"

volumes:
    codeigniter_db_data:
